### PR TITLE
Remove the `extends` operator from the language

### PR DESCRIPTION
**Pull request by connec**
The `extends` operator allowed an arbitrary function to inherit from
another arbitrary function. As the same logic is no longer being used to
implement class inheritance the value of maintaining the `extends`
operator is up for debate.

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
It may not add anything now that we have proper classes, but removing it would seem to break backward compatibility for no real gain.

**Comment by connec** [comment]
I don't feel strongly either way. It just feels like quite a fringe feature when it's not also used for classes (e.g. proposals for things like merge operators, mixins, etc. tend to be closed with "this would be better fulfilled by a library").

As it doesn't impact https://github.com/jashkenas/coffeescript/pull/4354 I'll close this for now and leave the branch in case we want to revisit it later.

**Comment by GeoffreyBooth** [comment]
I guess the question is, how often is it used in the wild? To extend a regular function, I mean, not a class. If it’s undocumented and almost-never-used, then sure, let’s kill it. But if it could break lots of people’s code, that seems a high cost to pay for cleanup.

**Comment by connec** [comment]
It seems it is documented:

> The `extends` operator helps with proper prototype setup, and can be used to create an inheritance chain between any pair of constructor functions.

The only examples containing `extends` are class examples, though.

**Pull request closed without merging**
